// Comprehensive Bangladesh Railway Master Dataset: All Stations, Intercity & Commuter Trains, Fares & Helpers

export interface RailwayStation {
  name: string;
  nameBn: string;
  code: string;
  district: string;
}

export interface RailwayTrain {
  number: string;
  name: string;
  nameBn: string;
  fromStation: string;
  toStation: string;
  departureTime: string; // HH:mm (24h)
  arrivalTime: string;   // HH:mm (24h)
  offDay: string;
  fares: Record<string, number>;
}

export const RAILWAY_CLASSES: { code: string; label: string; labelBn: string; defaultFare: number }[] = [
  { code: 'S_CHAIR', label: 'S_CHAIR', labelBn: 'শো.চেয়ার', defaultFare: 450 },
  { code: 'SNIGDHA', label: 'SNIGDHA', labelBn: 'স্নিগ্ধা', defaultFare: 865 },
  { code: 'AC_S', label: 'AC_S', labelBn: 'এসি সিট', defaultFare: 1035 },
  { code: 'AC_B', label: 'AC_B', labelBn: 'এসি বার্থ', defaultFare: 1555 },
  { code: 'F_BERTH', label: 'F_BERTH', labelBn: 'এফ_বার্থ', defaultFare: 1100 },
  { code: 'F_SEAT', label: 'F_SEAT', labelBn: 'ফার্স্ট সিট', defaultFare: 750 },
  { code: 'SHOVON', label: 'SHOVON', labelBn: 'শোভন', defaultFare: 375 },
  { code: 'AC_CHAIR', label: 'AC_CHAIR', labelBn: 'এসি চেয়ার', defaultFare: 865 },
  { code: 'SHULOV', label: 'SHULOV', labelBn: 'সুলভ', defaultFare: 180 },
];

export const RAILWAY_STATIONS: RailwayStation[] = [
  // Dhaka Division
  { name: 'Dhaka', nameBn: 'ঢাকা', code: 'DA', district: 'Dhaka' },
  { name: 'Dhaka Biman Bandar', nameBn: 'ঢাকা বিমান বন্দর', code: 'BBA', district: 'Dhaka' },
  { name: 'Dhaka Cantonment', nameBn: 'ঢাকা ক্যান্টনমেন্ট', code: 'DAC', district: 'Dhaka' },
  { name: 'Tejgaon', nameBn: 'তেজগাঁও', code: 'TJG', district: 'Dhaka' },
  { name: 'Gandaria', nameBn: 'গেন্ডারিয়া', code: 'GDA', district: 'Dhaka' },
  { name: 'Tongi', nameBn: 'টঙ্গী', code: 'TGI', district: 'Gazipur' },
  { name: 'Joydebpur', nameBn: 'জয়দেবপুর', code: 'JDP', district: 'Gazipur' },
  { name: 'Gazipur', nameBn: 'গাজীপুর', code: 'GZP', district: 'Gazipur' },
  { name: 'Narsingdi', nameBn: 'নরসিংদী', code: 'NSD', district: 'Narsingdi' },
  { name: 'Ghorashal', nameBn: 'ঘোড়াশাল', code: 'GHS', district: 'Narsingdi' },
  { name: 'Methikanda', nameBn: 'মেথিকান্দা', code: 'MKD', district: 'Narsingdi' },
  { name: 'Bhairab Bazar', nameBn: 'ভৈরব বাজার', code: 'BBR', district: 'Kishoreganj' },
  { name: 'Kishoreganj', nameBn: 'কিশোরগঞ্জ', code: 'KSG', district: 'Kishoreganj' },
  { name: 'Kuliarchar', nameBn: 'কুলিয়ারচর', code: 'KLC', district: 'Kishoreganj' },
  { name: 'Bajitpur', nameBn: 'বাজিতপুর', code: 'BJP', district: 'Kishoreganj' },
  { name: 'Sararchar', nameBn: 'সরারচর', code: 'SRC', district: 'Kishoreganj' },
  { name: 'Manikkhali', nameBn: 'মানিকখালী', code: 'MKL', district: 'Kishoreganj' },
  { name: 'Tangail', nameBn: 'টাঙ্গাইল', code: 'TG', district: 'Tangail' },
  { name: 'Mirzapur', nameBn: 'মির্জাপুর', code: 'MZP', district: 'Tangail' },
  { name: 'Bangabandhu Setu East', nameBn: 'বঙ্গবন্ধু সেতু পূর্ব', code: 'BBE', district: 'Tangail' },
  { name: 'Bangabandhu Setu West', nameBn: 'বঙ্গবন্ধু সেতু পশ্চিম', code: 'BBW', district: 'Sirajganj' },
  { name: 'Faridpur', nameBn: 'ফরিদপুর', code: 'FDP', district: 'Faridpur' },
  { name: 'Bhanga', nameBn: 'ভাঙ্গা', code: 'BNG', district: 'Faridpur' },
  { name: 'Bhanga Junction', nameBn: 'ভাঙ্গা জংশন', code: 'BNJ', district: 'Faridpur' },
  { name: 'Rajbari', nameBn: 'রাজবাড়ী', code: 'RJB', district: 'Rajbari' },
  { name: 'Pangsha', nameBn: 'পাংশা', code: 'PGS', district: 'Rajbari' },
  { name: 'Goalando Ghat', nameBn: 'গোয়ালন্দ ঘাট', code: 'GLG', district: 'Rajbari' },
  { name: 'Padma', nameBn: 'পদ্মা', code: 'PDM', district: 'Munshiganj' },
  { name: 'Mawa', nameBn: 'মাওয়া', code: 'MWA', district: 'Munshiganj' },
  { name: 'Shibchar', nameBn: 'শিবচর', code: 'SBC', district: 'Madaripur' },
  { name: 'Madaripur', nameBn: 'মাদারীপুর', code: 'MDP', district: 'Madaripur' },
  { name: 'Gopalganj', nameBn: 'গোপালগঞ্জ', code: 'GPJ', district: 'Gopalganj' },
  { name: 'Kashiani Junction', nameBn: 'কাশিয়ানী জংশন', code: 'KSJ', district: 'Gopalganj' },

  // Chittagong Division
  { name: 'Chittagong', nameBn: 'চট্টগ্রাম', code: 'CG', district: 'Chittagong' },
  { name: 'Chattogram Cantonment', nameBn: 'চট্টগ্রাম ক্যান্টনমেন্ট', code: 'CGC', district: 'Chittagong' },
  { name: 'Sitakunda', nameBn: 'সীতাকুণ্ড', code: 'SKD', district: 'Chittagong' },
  { name: 'Mirsharai', nameBn: 'মীরসরাই', code: 'MSR', district: 'Chittagong' },
  { name: 'Baraiyarhat', nameBn: 'বারৈয়ারহাট', code: 'BYH', district: 'Chittagong' },
  { name: 'Dohazari', nameBn: 'দোহাজারী', code: 'DHZ', district: 'Chittagong' },
  { name: 'Lohagara', nameBn: 'লোহাগাড়া', code: 'LHG', district: 'Chittagong' },
  { name: 'Harbang', nameBn: 'হারবাং', code: 'HBG', district: 'Cox\'s Bazar' },
  { name: 'Chakaria', nameBn: 'চকোরিয়া', code: 'CKR', district: 'Cox\'s Bazar' },
  { name: 'Dulahazra', nameBn: 'ডুলাহাজরা', code: 'DLH', district: 'Cox\'s Bazar' },
  { name: 'Islamabad', nameBn: 'ইসলামাবাদ', code: 'ISL', district: 'Cox\'s Bazar' },
  { name: 'Ramu', nameBn: 'রামু', code: 'RMU', district: 'Cox\'s Bazar' },
  { name: 'Cox\'s Bazar', nameBn: 'কক্সবাজার', code: 'CXB', district: 'Cox\'s Bazar' },
  { name: 'Feni', nameBn: 'ফেনী', code: 'FN', district: 'Feni' },
  { name: 'Muhuriganj', nameBn: 'মুহুরীগঞ্জ', code: 'MHG', district: 'Feni' },
  { name: 'Fazilpur', nameBn: 'ফাজিলপুর', code: 'FZP', district: 'Feni' },
  { name: 'Gunabati', nameBn: 'গুণবতী', code: 'GNB', district: 'Cumilla' },
  { name: 'Hasanpur', nameBn: 'হাসানপুর', code: 'HNP', district: 'Cumilla' },
  { name: 'Nangalkot', nameBn: 'নাঙ্গলকোট', code: 'NKT', district: 'Cumilla' },
  { name: 'Laksham', nameBn: 'লাকসাম', code: 'LKM', district: 'Cumilla' },
  { name: 'Cumilla', nameBn: 'কুমিল্লা', code: 'CUM', district: 'Cumilla' },
  { name: 'Brahmanbaria', nameBn: 'ব্রাহ্মণবাড়িয়া', code: 'BB', district: 'Brahmanbaria' },
  { name: 'Akhaura', nameBn: 'আখাউড়া', code: 'AKH', district: 'Brahmanbaria' },
  { name: 'Kasba', nameBn: 'কসবা', code: 'KSB', district: 'Brahmanbaria' },
  { name: 'Mandabag', nameBn: 'মন্দভাগ', code: 'MDB', district: 'Brahmanbaria' },
  { name: 'Chandpur', nameBn: 'চাঁদপুর', code: 'CDP', district: 'Chandpur' },
  { name: 'Chandpur Court', nameBn: 'চাঁদপুর কোর্ট', code: 'CPC', district: 'Chandpur' },
  { name: 'Hajiganj', nameBn: 'হাজীগঞ্জ', code: 'HJG', district: 'Chandpur' },
  { name: 'Noakhali', nameBn: 'নোয়াখালী', code: 'NKL', district: 'Noakhali' },
  { name: 'Maijdee Court', nameBn: 'মাইজদী কোর্ট', code: 'MJC', district: 'Noakhali' },
  { name: 'Sonaimuri', nameBn: 'সোনাইমুড়ী', code: 'SNM', district: 'Noakhali' },
  { name: 'Chowmuhani', nameBn: 'চৌমুহনী', code: 'CMH', district: 'Noakhali' },

  // Sylhet Division
  { name: 'Sylhet', nameBn: 'সিলেট', code: 'SY', district: 'Sylhet' },
  { name: 'Moglabazar', nameBn: 'মোগলাবাজার', code: 'MGB', district: 'Sylhet' },
  { name: 'Maijgaon', nameBn: 'মাইজগাঁও', code: 'MJG', district: 'Sylhet' },
  { name: 'Kulaura', nameBn: 'কুলাউড়া', code: 'KLR', district: 'Moulvibazar' },
  { name: 'Shamshernagar', nameBn: 'শমশেরনগর', code: 'SMN', district: 'Moulvibazar' },
  { name: 'Bhanugach', nameBn: 'ভানুগাছ', code: 'BNG', district: 'Moulvibazar' },
  { name: 'Srimangal', nameBn: 'শ্রীমঙ্গল', code: 'SMG', district: 'Moulvibazar' },
  { name: 'Shayestaganj', nameBn: 'শায়েস্তাগঞ্জ', code: 'STG', district: 'Habiganj' },
  { name: 'Nayapara', nameBn: 'নয়াপাড়া', code: 'NYP', district: 'Habiganj' },
  { name: 'Mantala', nameBn: 'মনতলা', code: 'MTL', district: 'Habiganj' },
  { name: 'Chhatak Bazar', nameBn: 'ছাতক বাজার', code: 'CTB', district: 'Sunamganj' },

  // Rajshahi Division
  { name: 'Rajshahi', nameBn: 'রাজশাহী', code: 'RJ', district: 'Rajshahi' },
  { name: 'Rajshahi Court', nameBn: 'রাজশাহী কোর্ট', code: 'RJC', district: 'Rajshahi' },
  { name: 'Sardah Road', nameBn: 'সারদা রোড', code: 'SRD', district: 'Rajshahi' },
  { name: 'Abdulpur', nameBn: 'আব্দুলপুর', code: 'ADP', district: 'Natore' },
  { name: 'Natore', nameBn: 'নাটোর', code: 'NTR', district: 'Natore' },
  { name: 'Ishwardi', nameBn: 'ঈশ্বরদী', code: 'ISD', district: 'Pabna' },
  { name: 'Ishwardi Bypass', nameBn: 'ঈশ্বরদী বাইপাস', code: 'IBP', district: 'Pabna' },
  { name: 'Pabna', nameBn: 'পাবনা', code: 'PB', district: 'Pabna' },
  { name: 'Chatmohar', nameBn: 'চাটমোহর', code: 'CTM', district: 'Pabna' },
  { name: 'Pakshi', nameBn: 'পাকশী', code: 'PKS', district: 'Pabna' },
  { name: 'Ullapara', nameBn: 'উল্লাপাড়া', code: 'ULP', district: 'Sirajganj' },
  { name: 'Jamtail', nameBn: 'জামতৈল', code: 'JMT', district: 'Sirajganj' },
  { name: 'Sirajganj', nameBn: 'সিরাজগঞ্জ', code: 'SG', district: 'Sirajganj' },
  { name: 'Sirajganj Bazar', nameBn: 'সিরাজগঞ্জ বাজার', code: 'SGB', district: 'Sirajganj' },
  { name: 'Santahar', nameBn: 'সান্তাহার', code: 'STH', district: 'Bogra' },
  { name: 'Bogra', nameBn: 'বগুড়া', code: 'BG', district: 'Bogra' },
  { name: 'Sonatola', nameBn: 'সোনাতলা', code: 'SNT', district: 'Bogra' },
  { name: 'Joypurhat', nameBn: 'জয়পুরহাট', code: 'JPH', district: 'Joypurhat' },
  { name: 'Panchbibi', nameBn: 'পাঁচবিবি', code: 'PCB', district: 'Joypurhat' },

  // Rangpur Division
  { name: 'Rangpur', nameBn: 'রংপুর', code: 'RP', district: 'Rangpur' },
  { name: 'Badarganj', nameBn: 'বদরগঞ্জ', code: 'BDG', district: 'Rangpur' },
  { name: 'Kaunia', nameBn: 'কাউনিয়া', code: 'KNA', district: 'Rangpur' },
  { name: 'Kurigram', nameBn: 'কুড়িগ্রাম', code: 'KRG', district: 'Kurigram' },
  { name: 'Chilmari', nameBn: 'চিলমারী', code: 'CLM', district: 'Kurigram' },
  { name: 'Lalmonirhat', nameBn: 'লালমনিরহাট', code: 'LMH', district: 'Lalmonirhat' },
  { name: 'Patgram', nameBn: 'পাটগ্রাম', code: 'PTG', district: 'Lalmonirhat' },
  { name: 'Burimari', nameBn: 'বুড়িমারী', code: 'BRM', district: 'Lalmonirhat' },
  { name: 'Gaibandha', nameBn: 'গাইবান্ধা', code: 'GBN', district: 'Gaibandha' },
  { name: 'Bonarpara', nameBn: 'বোনারপাড়া', code: 'BNP', district: 'Gaibandha' },
  { name: 'Bamandanga', nameBn: 'বামনডাঙ্গা', code: 'BMD', district: 'Gaibandha' },
  { name: 'Mahimaganj', nameBn: 'মহিমাগঞ্জ', code: 'MHJ', district: 'Gaibandha' },
  { name: 'Saidpur', nameBn: 'সৈয়দপুর', code: 'SPD', district: 'Nilphamari' },
  { name: 'Nilphamari', nameBn: 'নীলফামারী', code: 'NLP', district: 'Nilphamari' },
  { name: 'Domar', nameBn: 'ডোমার', code: 'DMR', district: 'Nilphamari' },
  { name: 'Chilahati', nameBn: 'চিলাহাটি', code: 'CLH', district: 'Nilphamari' },
  { name: 'Parbatipur', nameBn: 'পার্বতীপুর', code: 'PBP', district: 'Dinajpur' },
  { name: 'Dinajpur', nameBn: 'দিনাজপুর', code: 'DJ', district: 'Dinajpur' },
  { name: 'Birampur', nameBn: 'বিরামপুর', code: 'BMP', district: 'Dinajpur' },
  { name: 'Fulbari', nameBn: 'ফুলবাড়ী', code: 'FLB', district: 'Dinajpur' },
  { name: 'Setabganj', nameBn: 'সেতাবগঞ্জ', code: 'STB', district: 'Dinajpur' },
  { name: 'Pirganj', nameBn: 'পীরগঞ্জ', code: 'PRG', district: 'Thakurgaon' },
  { name: 'Thakurgaon Road', nameBn: 'ঠাকুরগাঁও রোড', code: 'TKR', district: 'Thakurgaon' },
  { name: 'Ruhia', nameBn: 'রুহিয়া', code: 'RHA', district: 'Thakurgaon' },
  { name: 'Shibganj', nameBn: 'শিবগঞ্জ', code: 'SBJ', district: 'Thakurgaon' },
  { name: 'Panchagarh', nameBn: 'পঞ্চগড়', code: 'PG', district: 'Panchagarh' },

  // Khulna Division
  { name: 'Khulna', nameBn: 'খুলনা', code: 'KL', district: 'Khulna' },
  { name: 'Daulatpur', nameBn: 'দৌলতপুর', code: 'DLP', district: 'Khulna' },
  { name: 'Phultala', nameBn: 'ফুলতলা', code: 'PLT', district: 'Khulna' },
  { name: 'Noapara', nameBn: 'নওয়াপাড়া', code: 'NWP', district: 'Jashore' },
  { name: 'Jashore', nameBn: 'যশোর', code: 'JSR', district: 'Jashore' },
  { name: 'Jhikargachha', nameBn: 'ঝিকরগাছা', code: 'JKG', district: 'Jashore' },
  { name: 'Benapole', nameBn: 'বেনাপোল', code: 'BNP', district: 'Jashore' },
  { name: 'Kotchandpur', nameBn: 'কোটচাঁদপুর', code: 'KCP', district: 'Jhenaidah' },
  { name: 'Mubarakganj', nameBn: 'মোবারকগঞ্জ', code: 'MBG', district: 'Jhenaidah' },
  { name: 'Safdarpur', nameBn: 'সফদারপুর', code: 'SFP', district: 'Jhenaidah' },
  { name: 'Chuadanga', nameBn: 'চুয়াডাঙ্গা', code: 'CDG', district: 'Chuadanga' },
  { name: 'Darshana', nameBn: 'দর্শনা', code: 'DSN', district: 'Chuadanga' },
  { name: 'Darshana Halt', nameBn: 'দর্শনা হল্ট', code: 'DSH', district: 'Chuadanga' },
  { name: 'Alamdanga', nameBn: 'আলমডাঙ্গা', code: 'ALD', district: 'Chuadanga' },
  { name: 'Poradaha', nameBn: 'পোড়াদহ', code: 'PRD', district: 'Kushtia' },
  { name: 'Kushtia', nameBn: 'কুষ্টিয়া', code: 'KST', district: 'Kushtia' },
  { name: 'Kushtia Court', nameBn: 'কুষ্টিয়া কোর্ট', code: 'KSC', district: 'Kushtia' },
  { name: 'Bheramara', nameBn: 'ভেড়ামারা', code: 'VRM', district: 'Kushtia' },
  { name: 'Narail', nameBn: 'নড়াইল', code: 'NRL', district: 'Narail' },
  { name: 'Magura', nameBn: 'মাগুরা', code: 'MGR', district: 'Magura' },
  { name: 'Meherpur', nameBn: 'মেহেরপুর', code: 'MHP', district: 'Meherpur' },

  // Mymensingh Division
  { name: 'Mymensingh', nameBn: 'ময়মনসিংহ', code: 'MS', district: 'Mymensingh' },
  { name: 'Gafargaon', nameBn: 'গফরগাঁও', code: 'GFG', district: 'Mymensingh' },
  { name: 'Gouripur', nameBn: 'গৌরীপুর', code: 'GRP', district: 'Mymensingh' },
  { name: 'Piyarpur', nameBn: 'পিয়ারপুর', code: 'PYP', district: 'Mymensingh' },
  { name: 'Jamalpur', nameBn: 'জামালপুর', code: 'JML', district: 'Jamalpur' },
  { name: 'Sarishabari', nameBn: 'সরিষাবাড়ী', code: 'SSB', district: 'Jamalpur' },
  { name: 'Tarakandi', nameBn: 'তারাকান্দি', code: 'TKD', district: 'Jamalpur' },
  { name: 'Adv. Motiur Rahman', nameBn: 'এডভোকেট মতিউর রহমান', code: 'AMR', district: 'Jamalpur' },
  { name: 'Dewanganj Bazar', nameBn: 'দেওয়ানগঞ্জ বাজার', code: 'DGB', district: 'Jamalpur' },
  { name: 'Bahadurabad Ghat', nameBn: 'বাহাদুরাবাদ ঘাট', code: 'BBG', district: 'Jamalpur' },
  { name: 'Netrokona', nameBn: 'নেত্রকোণা', code: 'NTK', district: 'Netrokona' },
  { name: 'Mohanganj', nameBn: 'মোহনগঞ্জ', code: 'MHG', district: 'Netrokona' },
  { name: 'Barhatta', nameBn: 'বারহাট্টা', code: 'BHT', district: 'Netrokona' },
  { name: 'Kendua', nameBn: 'কেন্দুয়া', code: 'KND', district: 'Netrokona' },
];

export const RAILWAY_TRAINS: RailwayTrain[] = [
  // ─── Dhaka <-> Rajshahi ───
  {
    number: '760',
    name: 'PADMA EXPRESS',
    nameBn: 'পদ্মা এক্সপ্রেস',
    fromStation: 'Rajshahi',
    toStation: 'Dhaka',
    departureTime: '16:00',
    arrivalTime: '21:40',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 450, SNIGDHA: 865, AC_S: 1035, AC_B: 1555, SHOVON: 375 },
  },
  {
    number: '759',
    name: 'PADMA EXPRESS',
    nameBn: 'পদ্মা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Rajshahi',
    departureTime: '23:00',
    arrivalTime: '04:30',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 450, SNIGDHA: 865, AC_S: 1035, AC_B: 1555, SHOVON: 375 },
  },
  {
    number: '754',
    name: 'SILKCITY EXPRESS',
    nameBn: 'সিল্কসিটি এক্সপ্রেস',
    fromStation: 'Rajshahi',
    toStation: 'Dhaka',
    departureTime: '07:40',
    arrivalTime: '13:30',
    offDay: 'Sunday',
    fares: { S_CHAIR: 450, SNIGDHA: 865, AC_S: 1035, AC_B: 1555, SHOVON: 375 },
  },
  {
    number: '753',
    name: 'SILKCITY EXPRESS',
    nameBn: 'সিল্কসিটি এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Rajshahi',
    departureTime: '14:45',
    arrivalTime: '20:35',
    offDay: 'Sunday',
    fares: { S_CHAIR: 450, SNIGDHA: 865, AC_S: 1035, AC_B: 1555, SHOVON: 375 },
  },
  {
    number: '770',
    name: 'DHUMKETU EXPRESS',
    nameBn: 'ধূমকেতু এক্সপ্রেস',
    fromStation: 'Rajshahi',
    toStation: 'Dhaka',
    departureTime: '23:20',
    arrivalTime: '04:55',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 450, SNIGDHA: 865, AC_S: 1035, AC_B: 1555, SHOVON: 375 },
  },
  {
    number: '769',
    name: 'DHUMKETU EXPRESS',
    nameBn: 'ধূমকেতু এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Rajshahi',
    departureTime: '06:00',
    arrivalTime: '11:40',
    offDay: 'Thursday',
    fares: { S_CHAIR: 450, SNIGDHA: 865, AC_S: 1035, AC_B: 1555, SHOVON: 375 },
  },
  {
    number: '792',
    name: 'BANA LATA EXPRESS',
    nameBn: 'বনলতা এক্সপ্রেস',
    fromStation: 'Rajshahi',
    toStation: 'Dhaka',
    departureTime: '06:00',
    arrivalTime: '10:45',
    offDay: 'Friday',
    fares: { S_CHAIR: 525, SNIGDHA: 1000, AC_S: 1200, AC_B: 1800, SHOVON: 440 },
  },
  {
    number: '791',
    name: 'BANA LATA EXPRESS',
    nameBn: 'বনলতা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Rajshahi',
    departureTime: '13:30',
    arrivalTime: '18:15',
    offDay: 'Friday',
    fares: { S_CHAIR: 525, SNIGDHA: 1000, AC_S: 1200, AC_B: 1800, SHOVON: 440 },
  },
  {
    number: '755',
    name: 'MADHUMATI EXPRESS',
    nameBn: 'মধুমতী এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Rajshahi',
    departureTime: '15:00',
    arrivalTime: '21:30',
    offDay: 'Thursday',
    fares: { S_CHAIR: 460, SNIGDHA: 880, AC_S: 1050, SHOVON: 380 },
  },
  {
    number: '756',
    name: 'MADHUMATI EXPRESS',
    nameBn: 'মধুমতী এক্সপ্রেস',
    fromStation: 'Rajshahi',
    toStation: 'Dhaka',
    departureTime: '06:40',
    arrivalTime: '13:20',
    offDay: 'Thursday',
    fares: { S_CHAIR: 460, SNIGDHA: 880, AC_S: 1050, SHOVON: 380 },
  },

  // ─── Dhaka <-> Chittagong ───
  {
    number: '702',
    name: 'SUBORNO EXPRESS',
    nameBn: 'সুবর্ণ এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Chittagong',
    departureTime: '16:30',
    arrivalTime: '21:50',
    offDay: 'Monday',
    fares: { S_CHAIR: 500, SNIGDHA: 960, AC_S: 1150, SHOVON: 420 },
  },
  {
    number: '701',
    name: 'SUBORNO EXPRESS',
    nameBn: 'সুবর্ণ এক্সপ্রেস',
    fromStation: 'Chittagong',
    toStation: 'Dhaka',
    departureTime: '07:00',
    arrivalTime: '12:20',
    offDay: 'Monday',
    fares: { S_CHAIR: 500, SNIGDHA: 960, AC_S: 1150, SHOVON: 420 },
  },
  {
    number: '788',
    name: 'SONAR BANGLA EXPRESS',
    nameBn: 'সোনার বাংলা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Chittagong',
    departureTime: '07:00',
    arrivalTime: '12:15',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 520, SNIGDHA: 1000, AC_S: 1200, SHOVON: 430 },
  },
  {
    number: '787',
    name: 'SONAR BANGLA EXPRESS',
    nameBn: 'সোনার বাংলা এক্সপ্রেস',
    fromStation: 'Chittagong',
    toStation: 'Dhaka',
    departureTime: '17:00',
    arrivalTime: '22:15',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 520, SNIGDHA: 1000, AC_S: 1200, SHOVON: 430 },
  },
  {
    number: '704',
    name: 'MOHANAGAR PROVATI',
    nameBn: 'মহানগর প্রভাতী',
    fromStation: 'Dhaka',
    toStation: 'Chittagong',
    departureTime: '07:45',
    arrivalTime: '14:00',
    offDay: 'None',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, SHOVON: 360 },
  },
  {
    number: '703',
    name: 'MOHANAGAR GODHULI',
    nameBn: 'মহানগর গোধূলী',
    fromStation: 'Chittagong',
    toStation: 'Dhaka',
    departureTime: '15:00',
    arrivalTime: '21:15',
    offDay: 'None',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, SHOVON: 360 },
  },
  {
    number: '722',
    name: 'MOHANAGAR EXPRESS',
    nameBn: 'মহানগর এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Chittagong',
    departureTime: '21:20',
    arrivalTime: '04:15',
    offDay: 'Sunday',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, SHOVON: 360 },
  },
  {
    number: '721',
    name: 'MOHANAGAR EXPRESS',
    nameBn: 'মহানগর এক্সপ্রেস',
    fromStation: 'Chittagong',
    toStation: 'Dhaka',
    departureTime: '12:30',
    arrivalTime: '19:10',
    offDay: 'Sunday',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, SHOVON: 360 },
  },
  {
    number: '742',
    name: 'TURNA EXPRESS',
    nameBn: 'তূর্ণা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Chittagong',
    departureTime: '23:30',
    arrivalTime: '05:40',
    offDay: 'None',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, AC_B: 1515, SHOVON: 360 },
  },
  {
    number: '741',
    name: 'TURNA EXPRESS',
    nameBn: 'তূর্ণা এক্সপ্রেস',
    fromStation: 'Chittagong',
    toStation: 'Dhaka',
    departureTime: '23:00',
    arrivalTime: '05:15',
    offDay: 'None',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, AC_B: 1515, SHOVON: 360 },
  },
  {
    number: '68',
    name: 'CHATTALA EXPRESS',
    nameBn: 'চট্টলা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Chittagong',
    departureTime: '13:45',
    arrivalTime: '20:30',
    offDay: 'Friday',
    fares: { S_CHAIR: 380, SNIGDHA: 730, SHOVON: 310 },
  },
  {
    number: '67',
    name: 'CHATTALA EXPRESS',
    nameBn: 'চট্টলা এক্সপ্রেস',
    fromStation: 'Chittagong',
    toStation: 'Dhaka',
    departureTime: '06:00',
    arrivalTime: '12:50',
    offDay: 'Friday',
    fares: { S_CHAIR: 380, SNIGDHA: 730, SHOVON: 310 },
  },

  // ─── Dhaka <-> Cox's Bazar ───
  {
    number: '814',
    name: 'COX\'S BAZAR EXPRESS',
    nameBn: 'কক্সবাজার এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Cox\'s Bazar',
    departureTime: '22:30',
    arrivalTime: '06:40',
    offDay: 'Monday',
    fares: { S_CHAIR: 695, SNIGDHA: 1325, AC_S: 1590, AC_B: 2380, SHOVON: 590 },
  },
  {
    number: '813',
    name: 'COX\'S BAZAR EXPRESS',
    nameBn: 'কক্সবাজার এক্সপ্রেস',
    fromStation: 'Cox\'s Bazar',
    toStation: 'Dhaka',
    departureTime: '12:30',
    arrivalTime: '21:10',
    offDay: 'Monday',
    fares: { S_CHAIR: 695, SNIGDHA: 1325, AC_S: 1590, AC_B: 2380, SHOVON: 590 },
  },
  {
    number: '816',
    name: 'PARJATAK EXPRESS',
    nameBn: 'পর্যটক এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Cox\'s Bazar',
    departureTime: '06:15',
    arrivalTime: '15:00',
    offDay: 'Sunday',
    fares: { S_CHAIR: 695, SNIGDHA: 1325, AC_S: 1590, AC_B: 2380, SHOVON: 590 },
  },
  {
    number: '815',
    name: 'PARJATAK EXPRESS',
    nameBn: 'পর্যটক এক্সপ্রেস',
    fromStation: 'Cox\'s Bazar',
    toStation: 'Dhaka',
    departureTime: '20:00',
    arrivalTime: '04:30',
    offDay: 'Sunday',
    fares: { S_CHAIR: 695, SNIGDHA: 1325, AC_S: 1590, AC_B: 2380, SHOVON: 590 },
  },

  // ─── Dhaka <-> Sylhet ───
  {
    number: '709',
    name: 'PARABAT EXPRESS',
    nameBn: 'পারাবত এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Sylhet',
    departureTime: '06:20',
    arrivalTime: '13:00',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 410, SNIGDHA: 785, AC_S: 940, SHOVON: 345 },
  },
  {
    number: '710',
    name: 'PARABAT EXPRESS',
    nameBn: 'পারাবত এক্সপ্রেস',
    fromStation: 'Sylhet',
    toStation: 'Dhaka',
    departureTime: '15:45',
    arrivalTime: '22:40',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 410, SNIGDHA: 785, AC_S: 940, SHOVON: 345 },
  },
  {
    number: '717',
    name: 'JAYANTIKA EXPRESS',
    nameBn: 'জয়ন্তিকা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Sylhet',
    departureTime: '11:15',
    arrivalTime: '19:00',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 410, SNIGDHA: 785, AC_S: 940, SHOVON: 345 },
  },
  {
    number: '718',
    name: 'JAYANTIKA EXPRESS',
    nameBn: 'জয়ন্তিকা এক্সপ্রেস',
    fromStation: 'Sylhet',
    toStation: 'Dhaka',
    departureTime: '08:45',
    arrivalTime: '16:00',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 410, SNIGDHA: 785, AC_S: 940, SHOVON: 345 },
  },
  {
    number: '739',
    name: 'UPABAN EXPRESS',
    nameBn: 'উপবন এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Sylhet',
    departureTime: '20:30',
    arrivalTime: '05:00',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 410, SNIGDHA: 785, AC_S: 940, AC_B: 1410, SHOVON: 345 },
  },
  {
    number: '740',
    name: 'UPABAN EXPRESS',
    nameBn: 'উপবন এক্সপ্রেস',
    fromStation: 'Sylhet',
    toStation: 'Dhaka',
    departureTime: '23:00',
    arrivalTime: '06:45',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 410, SNIGDHA: 785, AC_S: 940, AC_B: 1410, SHOVON: 345 },
  },
  {
    number: '773',
    name: 'KALNI EXPRESS',
    nameBn: 'কালনী এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Sylhet',
    departureTime: '13:00',
    arrivalTime: '19:45',
    offDay: 'Friday',
    fares: { S_CHAIR: 410, SNIGDHA: 785, AC_S: 940, SHOVON: 345 },
  },
  {
    number: '774',
    name: 'KALNI EXPRESS',
    nameBn: 'কালনী এক্সপ্রেস',
    fromStation: 'Sylhet',
    toStation: 'Dhaka',
    departureTime: '06:15',
    arrivalTime: '13:00',
    offDay: 'Friday',
    fares: { S_CHAIR: 410, SNIGDHA: 785, AC_S: 940, SHOVON: 345 },
  },

  // ─── Chittagong <-> Sylhet ───
  {
    number: '719',
    name: 'PAHARIKA EXPRESS',
    nameBn: 'পাহাড়িকা এক্সপ্রেস',
    fromStation: 'Chittagong',
    toStation: 'Sylhet',
    departureTime: '07:50',
    arrivalTime: '16:30',
    offDay: 'Monday',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, SHOVON: 365 },
  },
  {
    number: '720',
    name: 'PAHARIKA EXPRESS',
    nameBn: 'পাহাড়িকা এক্সপ্রেস',
    fromStation: 'Sylhet',
    toStation: 'Chittagong',
    departureTime: '10:15',
    arrivalTime: '19:45',
    offDay: 'Monday',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, SHOVON: 365 },
  },
  {
    number: '723',
    name: 'UDAYAN EXPRESS',
    nameBn: 'উদয়ন এক্সপ্রেস',
    fromStation: 'Chittagong',
    toStation: 'Sylhet',
    departureTime: '21:45',
    arrivalTime: '06:00',
    offDay: 'Sunday',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, AC_B: 1515, SHOVON: 365 },
  },
  {
    number: '724',
    name: 'UDAYAN EXPRESS',
    nameBn: 'উদয়ন এক্সপ্রেস',
    fromStation: 'Sylhet',
    toStation: 'Chittagong',
    departureTime: '21:20',
    arrivalTime: '05:30',
    offDay: 'Sunday',
    fares: { S_CHAIR: 440, SNIGDHA: 845, AC_S: 1010, AC_B: 1515, SHOVON: 365 },
  },

  // ─── Dhaka <-> Khulna / Benapole ───
  {
    number: '726',
    name: 'SUNDARBAN EXPRESS',
    nameBn: 'সুন্দরবন এক্সপ্রেস',
    fromStation: 'Khulna',
    toStation: 'Dhaka',
    departureTime: '21:45',
    arrivalTime: '06:10',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 530, SNIGDHA: 1015, AC_S: 1220, AC_B: 1830, SHOVON: 440 },
  },
  {
    number: '725',
    name: 'SUNDARBAN EXPRESS',
    nameBn: 'সুন্দরবন এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Khulna',
    departureTime: '08:15',
    arrivalTime: '16:00',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 530, SNIGDHA: 1015, AC_S: 1220, AC_B: 1830, SHOVON: 440 },
  },
  {
    number: '764',
    name: 'CHITRA EXPRESS',
    nameBn: 'চিত্রা এক্সপ্রেস',
    fromStation: 'Khulna',
    toStation: 'Dhaka',
    departureTime: '09:00',
    arrivalTime: '17:55',
    offDay: 'Monday',
    fares: { S_CHAIR: 530, SNIGDHA: 1015, AC_S: 1220, AC_B: 1830, SHOVON: 440 },
  },
  {
    number: '763',
    name: 'CHITRA EXPRESS',
    nameBn: 'চিত্রা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Khulna',
    departureTime: '19:00',
    arrivalTime: '03:40',
    offDay: 'Monday',
    fares: { S_CHAIR: 530, SNIGDHA: 1015, AC_S: 1220, AC_B: 1830, SHOVON: 440 },
  },
  {
    number: '796',
    name: 'BENAPOLE EXPRESS',
    nameBn: 'বেনাপোল এক্সপ্রেস',
    fromStation: 'Benapole',
    toStation: 'Dhaka',
    departureTime: '13:00',
    arrivalTime: '20:45',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 535, SNIGDHA: 1025, AC_S: 1230, AC_B: 1845, SHOVON: 445 },
  },
  {
    number: '795',
    name: 'BENAPOLE EXPRESS',
    nameBn: 'বেনাপোল এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Benapole',
    departureTime: '23:15',
    arrivalTime: '07:20',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 535, SNIGDHA: 1025, AC_S: 1230, AC_B: 1845, SHOVON: 445 },
  },

  // ─── Khulna <-> Rajshahi ───
  {
    number: '762',
    name: 'SAGORDARI EXPRESS',
    nameBn: 'সাগরদাঁড়ী এক্সপ্রেস',
    fromStation: 'Khulna',
    toStation: 'Rajshahi',
    departureTime: '16:00',
    arrivalTime: '22:00',
    offDay: 'Monday',
    fares: { S_CHAIR: 380, SNIGDHA: 730, SHOVON: 315 },
  },
  {
    number: '761',
    name: 'SAGORDARI EXPRESS',
    nameBn: 'সাগরদাঁড়ী এক্সপ্রেস',
    fromStation: 'Rajshahi',
    toStation: 'Khulna',
    departureTime: '06:00',
    arrivalTime: '12:00',
    offDay: 'Monday',
    fares: { S_CHAIR: 380, SNIGDHA: 730, SHOVON: 315 },
  },
  {
    number: '716',
    name: 'KAPOTAKKHA EXPRESS',
    nameBn: 'কপোতাক্ষ এক্সপ্রেস',
    fromStation: 'Khulna',
    toStation: 'Rajshahi',
    departureTime: '06:15',
    arrivalTime: '12:15',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 380, SNIGDHA: 730, SHOVON: 315 },
  },
  {
    number: '715',
    name: 'KAPOTAKKHA EXPRESS',
    nameBn: 'কপোতাক্ষ এক্সপ্রেস',
    fromStation: 'Rajshahi',
    toStation: 'Khulna',
    departureTime: '14:30',
    arrivalTime: '20:30',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 380, SNIGDHA: 730, SHOVON: 315 },
  },

  // ─── Khulna <-> Chilahati ───
  {
    number: '727',
    name: 'RUPSHA EXPRESS',
    nameBn: 'রূপসা এক্সপ্রেস',
    fromStation: 'Khulna',
    toStation: 'Chilahati',
    departureTime: '07:15',
    arrivalTime: '17:00',
    offDay: 'Thursday',
    fares: { S_CHAIR: 540, SNIGDHA: 1030, SHOVON: 450 },
  },
  {
    number: '728',
    name: 'RUPSHA EXPRESS',
    nameBn: 'রূপসা এক্সপ্রেস',
    fromStation: 'Chilahati',
    toStation: 'Khulna',
    departureTime: '08:30',
    arrivalTime: '18:15',
    offDay: 'Thursday',
    fares: { S_CHAIR: 540, SNIGDHA: 1030, SHOVON: 450 },
  },
  {
    number: '747',
    name: 'SIMANTA EXPRESS',
    nameBn: 'সীমান্ত এক্সপ্রেস',
    fromStation: 'Khulna',
    toStation: 'Chilahati',
    departureTime: '21:15',
    arrivalTime: '06:40',
    offDay: 'None',
    fares: { S_CHAIR: 540, SNIGDHA: 1030, AC_B: 1850, SHOVON: 450 },
  },
  {
    number: '748',
    name: 'SIMANTA EXPRESS',
    nameBn: 'সীমান্ত এক্সপ্রেস',
    fromStation: 'Chilahati',
    toStation: 'Khulna',
    departureTime: '19:00',
    arrivalTime: '04:30',
    offDay: 'None',
    fares: { S_CHAIR: 540, SNIGDHA: 1030, AC_B: 1850, SHOVON: 450 },
  },

  // ─── Rajshahi <-> Chilahati ───
  {
    number: '731',
    name: 'BARENDRA EXPRESS',
    nameBn: 'বরেন্দ্র এক্সপ্রেস',
    fromStation: 'Rajshahi',
    toStation: 'Chilahati',
    departureTime: '15:00',
    arrivalTime: '21:40',
    offDay: 'Sunday',
    fares: { S_CHAIR: 345, SNIGDHA: 660, SHOVON: 290 },
  },
  {
    number: '732',
    name: 'BARENDRA EXPRESS',
    nameBn: 'বরেন্দ্র এক্সপ্রেস',
    fromStation: 'Chilahati',
    toStation: 'Rajshahi',
    departureTime: '05:50',
    arrivalTime: '12:30',
    offDay: 'Sunday',
    fares: { S_CHAIR: 345, SNIGDHA: 660, SHOVON: 290 },
  },
  {
    number: '733',
    name: 'TITUMIR EXPRESS',
    nameBn: 'তিতুমীর এক্সপ্রেস',
    fromStation: 'Rajshahi',
    toStation: 'Chilahati',
    departureTime: '06:20',
    arrivalTime: '13:00',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 345, SNIGDHA: 660, SHOVON: 290 },
  },
  {
    number: '734',
    name: 'TITUMIR EXPRESS',
    nameBn: 'তিতুমীর এক্সপ্রেস',
    fromStation: 'Chilahati',
    toStation: 'Rajshahi',
    departureTime: '14:20',
    arrivalTime: '21:00',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 345, SNIGDHA: 660, SHOVON: 290 },
  },

  // ─── Dhaka <-> Northern Region (Rangpur, Dinajpur, Panchagarh, Kurigram, Lalmonirhat, Chilahati) ───
  {
    number: '706',
    name: 'EKOTA EXPRESS',
    nameBn: 'একতা এক্সপ্রেস',
    fromStation: 'Panchagarh',
    toStation: 'Dhaka',
    departureTime: '21:10',
    arrivalTime: '07:40',
    offDay: 'None',
    fares: { S_CHAIR: 635, SNIGDHA: 1220, AC_S: 1465, AC_B: 2195, SHOVON: 530 },
  },
  {
    number: '705',
    name: 'EKOTA EXPRESS',
    nameBn: 'একতা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Panchagarh',
    departureTime: '10:15',
    arrivalTime: '20:30',
    offDay: 'None',
    fares: { S_CHAIR: 635, SNIGDHA: 1220, AC_S: 1465, AC_B: 2195, SHOVON: 530 },
  },
  {
    number: '758',
    name: 'DRUTAJAN EXPRESS',
    nameBn: 'দ্রুতযান এক্সপ্রেস',
    fromStation: 'Panchagarh',
    toStation: 'Dhaka',
    departureTime: '08:10',
    arrivalTime: '18:50',
    offDay: 'None',
    fares: { S_CHAIR: 635, SNIGDHA: 1220, AC_S: 1465, AC_B: 2195, SHOVON: 530 },
  },
  {
    number: '757',
    name: 'DRUTAJAN EXPRESS',
    nameBn: 'দ্রুতযান এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Panchagarh',
    departureTime: '20:00',
    arrivalTime: '06:10',
    offDay: 'None',
    fares: { S_CHAIR: 635, SNIGDHA: 1220, AC_S: 1465, AC_B: 2195, SHOVON: 530 },
  },
  {
    number: '794',
    name: 'PANCHAGARH EXPRESS',
    nameBn: 'পঞ্চগড় এক্সপ্রেস',
    fromStation: 'Panchagarh',
    toStation: 'Dhaka',
    departureTime: '13:00',
    arrivalTime: '22:35',
    offDay: 'None',
    fares: { S_CHAIR: 650, SNIGDHA: 1250, AC_S: 1500, AC_B: 2250, SHOVON: 540 },
  },
  {
    number: '793',
    name: 'PANCHAGARH EXPRESS',
    nameBn: 'পঞ্চগড় এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Panchagarh',
    departureTime: '23:30',
    arrivalTime: '09:00',
    offDay: 'None',
    fares: { S_CHAIR: 650, SNIGDHA: 1250, AC_S: 1500, AC_B: 2250, SHOVON: 540 },
  },
  {
    number: '772',
    name: 'RANGPUR EXPRESS',
    nameBn: 'রংপুর এক্সপ্রেস',
    fromStation: 'Rangpur',
    toStation: 'Dhaka',
    departureTime: '20:00',
    arrivalTime: '06:05',
    offDay: 'Sunday',
    fares: { S_CHAIR: 560, SNIGDHA: 1075, AC_S: 1290, AC_B: 1935, SHOVON: 465 },
  },
  {
    number: '771',
    name: 'RANGPUR EXPRESS',
    nameBn: 'রংপুর এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Rangpur',
    departureTime: '09:10',
    arrivalTime: '19:05',
    offDay: 'Monday',
    fares: { S_CHAIR: 560, SNIGDHA: 1075, AC_S: 1290, AC_B: 1935, SHOVON: 465 },
  },
  {
    number: '798',
    name: 'KURIGRAM EXPRESS',
    nameBn: 'কুড়িগ্রাম এক্সপ্রেস',
    fromStation: 'Kurigram',
    toStation: 'Dhaka',
    departureTime: '07:15',
    arrivalTime: '17:25',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 560, SNIGDHA: 1075, AC_S: 1290, SHOVON: 465 },
  },
  {
    number: '797',
    name: 'KURIGRAM EXPRESS',
    nameBn: 'কুড়িগ্রাম এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Kurigram',
    departureTime: '20:45',
    arrivalTime: '06:15',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 560, SNIGDHA: 1075, AC_S: 1290, SHOVON: 465 },
  },
  {
    number: '752',
    name: 'LALMONI EXPRESS',
    nameBn: 'লালমনি এক্সপ্রেস',
    fromStation: 'Lalmonirhat',
    toStation: 'Dhaka',
    departureTime: '09:50',
    arrivalTime: '20:45',
    offDay: 'Friday',
    fares: { S_CHAIR: 555, SNIGDHA: 1065, AC_S: 1275, AC_B: 1915, SHOVON: 460 },
  },
  {
    number: '751',
    name: 'LALMONI EXPRESS',
    nameBn: 'লালমনি এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Lalmonirhat',
    departureTime: '21:45',
    arrivalTime: '07:20',
    offDay: 'Friday',
    fares: { S_CHAIR: 555, SNIGDHA: 1065, AC_S: 1275, AC_B: 1915, SHOVON: 460 },
  },
  {
    number: '766',
    name: 'NILSAGAR EXPRESS',
    nameBn: 'নীলসাগর এক্সপ্রেস',
    fromStation: 'Chilahati',
    toStation: 'Dhaka',
    departureTime: '08:00',
    arrivalTime: '17:50',
    offDay: 'Monday',
    fares: { S_CHAIR: 575, SNIGDHA: 1100, AC_S: 1320, AC_B: 1980, SHOVON: 480 },
  },
  {
    number: '765',
    name: 'NILSAGAR EXPRESS',
    nameBn: 'নীলসাগর এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Chilahati',
    departureTime: '06:45',
    arrivalTime: '16:00',
    offDay: 'Monday',
    fares: { S_CHAIR: 575, SNIGDHA: 1100, AC_S: 1320, AC_B: 1980, SHOVON: 480 },
  },
  {
    number: '806',
    name: 'CHILAHATI EXPRESS',
    nameBn: 'চিলাহাটি এক্সপ্রেস',
    fromStation: 'Chilahati',
    toStation: 'Dhaka',
    departureTime: '22:00',
    arrivalTime: '07:15',
    offDay: 'Saturday',
    fares: { S_CHAIR: 575, SNIGDHA: 1100, AC_S: 1320, AC_B: 1980, SHOVON: 480 },
  },
  {
    number: '805',
    name: 'CHILAHATI EXPRESS',
    nameBn: 'চিলাহাটি এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Chilahati',
    departureTime: '17:00',
    arrivalTime: '02:30',
    offDay: 'Saturday',
    fares: { S_CHAIR: 575, SNIGDHA: 1100, AC_S: 1320, AC_B: 1980, SHOVON: 480 },
  },

  // ─── Dhaka <-> Mymensingh / Jamalpur / Dewanganj / Kishoreganj ───
  {
    number: '707',
    name: 'TEESTA EXPRESS',
    nameBn: 'তিস্তা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Dewanganj Bazar',
    departureTime: '07:30',
    arrivalTime: '12:50',
    offDay: 'Monday',
    fares: { S_CHAIR: 235, SNIGDHA: 450, AC_S: 540, SHOVON: 195 },
  },
  {
    number: '708',
    name: 'TEESTA EXPRESS',
    nameBn: 'তিস্তা এক্সপ্রেস',
    fromStation: 'Dewanganj Bazar',
    toStation: 'Dhaka',
    departureTime: '15:00',
    arrivalTime: '20:30',
    offDay: 'Monday',
    fares: { S_CHAIR: 235, SNIGDHA: 450, AC_S: 540, SHOVON: 195 },
  },
  {
    number: '743',
    name: 'BRAHMAPUTRA EXPRESS',
    nameBn: 'ব্রহ্মপুত্র এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Dewanganj Bazar',
    departureTime: '18:15',
    arrivalTime: '23:45',
    offDay: 'None',
    fares: { S_CHAIR: 235, SNIGDHA: 450, AC_S: 540, SHOVON: 195 },
  },
  {
    number: '744',
    name: 'BRAHMAPUTRA EXPRESS',
    nameBn: 'ব্রহ্মপুত্র এক্সপ্রেস',
    fromStation: 'Dewanganj Bazar',
    toStation: 'Dhaka',
    departureTime: '06:40',
    arrivalTime: '12:15',
    offDay: 'None',
    fares: { S_CHAIR: 235, SNIGDHA: 450, AC_S: 540, SHOVON: 195 },
  },
  {
    number: '735',
    name: 'AGNIBINA EXPRESS',
    nameBn: 'অগ্নিবীণা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Tarakandi',
    departureTime: '11:00',
    arrivalTime: '16:30',
    offDay: 'None',
    fares: { S_CHAIR: 220, SNIGDHA: 420, SHOVON: 180 },
  },
  {
    number: '736',
    name: 'AGNIBINA EXPRESS',
    nameBn: 'অগ্নিবীণা এক্সপ্রেস',
    fromStation: 'Tarakandi',
    toStation: 'Dhaka',
    departureTime: '17:50',
    arrivalTime: '23:15',
    offDay: 'None',
    fares: { S_CHAIR: 220, SNIGDHA: 420, SHOVON: 180 },
  },
  {
    number: '745',
    name: 'JAMUNA EXPRESS',
    nameBn: 'যমুনা এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Tarakandi',
    departureTime: '16:45',
    arrivalTime: '22:15',
    offDay: 'None',
    fares: { S_CHAIR: 220, SNIGDHA: 420, SHOVON: 180 },
  },
  {
    number: '746',
    name: 'JAMUNA EXPRESS',
    nameBn: 'যমুনা এক্সপ্রেস',
    fromStation: 'Tarakandi',
    toStation: 'Dhaka',
    departureTime: '02:00',
    arrivalTime: '07:30',
    offDay: 'None',
    fares: { S_CHAIR: 220, SNIGDHA: 420, SHOVON: 180 },
  },
  {
    number: '782',
    name: 'MOHANGANJ EXPRESS',
    nameBn: 'মোহনগঞ্জ এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Mohanganj',
    departureTime: '13:15',
    arrivalTime: '19:40',
    offDay: 'Monday',
    fares: { S_CHAIR: 245, SNIGDHA: 470, SHOVON: 200 },
  },
  {
    number: '781',
    name: 'MOHANGANJ EXPRESS',
    nameBn: 'মোহনগঞ্জ এক্সপ্রেস',
    fromStation: 'Mohanganj',
    toStation: 'Dhaka',
    departureTime: '23:00',
    arrivalTime: '05:30',
    offDay: 'Monday',
    fares: { S_CHAIR: 245, SNIGDHA: 470, SHOVON: 200 },
  },
  {
    number: '777',
    name: 'HAOR EXPRESS',
    nameBn: 'হাওর এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Mohanganj',
    departureTime: '22:15',
    arrivalTime: '05:00',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 245, SNIGDHA: 470, AC_B: 850, SHOVON: 200 },
  },
  {
    number: '778',
    name: 'HAOR EXPRESS',
    nameBn: 'হাওর এক্সপ্রেস',
    fromStation: 'Mohanganj',
    toStation: 'Dhaka',
    departureTime: '07:45',
    arrivalTime: '14:20',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 245, SNIGDHA: 470, AC_B: 850, SHOVON: 200 },
  },
  {
    number: '737',
    name: 'EGAROSINDHUR PROVATI',
    nameBn: 'এগারসিন্ধুর প্রভাতী',
    fromStation: 'Dhaka',
    toStation: 'Kishoreganj',
    departureTime: '07:15',
    arrivalTime: '11:15',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 195, SNIGDHA: 375, SHOVON: 160 },
  },
  {
    number: '738',
    name: 'EGAROSINDHUR PROVATI',
    nameBn: 'এগারসিন্ধুর প্রভাতী',
    fromStation: 'Kishoreganj',
    toStation: 'Dhaka',
    departureTime: '06:30',
    arrivalTime: '10:45',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 195, SNIGDHA: 375, SHOVON: 160 },
  },
  {
    number: '749',
    name: 'EGAROSINDHUR GODHULI',
    nameBn: 'এগারসিন্ধুর গোধূলী',
    fromStation: 'Dhaka',
    toStation: 'Kishoreganj',
    departureTime: '18:30',
    arrivalTime: '22:30',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 195, SNIGDHA: 375, SHOVON: 160 },
  },
  {
    number: '750',
    name: 'EGAROSINDHUR GODHULI',
    nameBn: 'এগারসিন্ধুর গোধূলী',
    fromStation: 'Kishoreganj',
    toStation: 'Dhaka',
    departureTime: '12:30',
    arrivalTime: '16:50',
    offDay: 'Wednesday',
    fares: { S_CHAIR: 195, SNIGDHA: 375, SHOVON: 160 },
  },
  {
    number: '781',
    name: 'KISHOREGANJ EXPRESS',
    nameBn: 'কিশোরগঞ্জ এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Kishoreganj',
    departureTime: '10:30',
    arrivalTime: '14:20',
    offDay: 'Friday',
    fares: { S_CHAIR: 195, SNIGDHA: 375, SHOVON: 160 },
  },
  {
    number: '782',
    name: 'KISHOREGANJ EXPRESS',
    nameBn: 'কিশোরগঞ্জ এক্সপ্রেস',
    fromStation: 'Kishoreganj',
    toStation: 'Dhaka',
    departureTime: '16:00',
    arrivalTime: '20:10',
    offDay: 'Friday',
    fares: { S_CHAIR: 195, SNIGDHA: 375, SHOVON: 160 },
  },

  // ─── Chittagong <-> Mymensingh ───
  {
    number: '785',
    name: 'BIJOY EXPRESS',
    nameBn: 'বিজয় এক্সপ্রেস',
    fromStation: 'Chittagong',
    toStation: 'Mymensingh',
    departureTime: '09:15',
    arrivalTime: '18:10',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 395, SNIGDHA: 755, SHOVON: 330 },
  },
  {
    number: '786',
    name: 'BIJOY EXPRESS',
    nameBn: 'বিজয় এক্সপ্রেস',
    fromStation: 'Mymensingh',
    toStation: 'Chittagong',
    departureTime: '20:30',
    arrivalTime: '05:00',
    offDay: 'Tuesday',
    fares: { S_CHAIR: 395, SNIGDHA: 755, SHOVON: 330 },
  },

  // ─── Dhaka <-> Sirajganj ───
  {
    number: '775',
    name: 'SIRAJGANJ EXPRESS',
    nameBn: 'সিরাজগঞ্জ এক্সপ্রেস',
    fromStation: 'Sirajganj Bazar',
    toStation: 'Dhaka',
    departureTime: '06:00',
    arrivalTime: '10:30',
    offDay: 'Saturday',
    fares: { S_CHAIR: 260, SNIGDHA: 500, SHOVON: 220 },
  },
  {
    number: '776',
    name: 'SIRAJGANJ EXPRESS',
    nameBn: 'সিরাজগঞ্জ এক্সপ্রেস',
    fromStation: 'Dhaka',
    toStation: 'Sirajganj Bazar',
    departureTime: '17:00',
    arrivalTime: '21:30',
    offDay: 'Saturday',
    fares: { S_CHAIR: 260, SNIGDHA: 500, SHOVON: 220 },
  },

  // ─── Chittagong <-> Chandpur ───
  {
    number: '729',
    name: 'MEGHNA EXPRESS',
    nameBn: 'মেঘনা এক্সপ্রেস',
    fromStation: 'Chittagong',
    toStation: 'Chandpur',
    departureTime: '17:15',
    arrivalTime: '21:50',
    offDay: 'None',
    fares: { S_CHAIR: 230, SNIGDHA: 440, SHOVON: 190 },
  },
  {
    number: '730',
    name: 'MEGHNA EXPRESS',
    nameBn: 'মেঘনা এক্সপ্রেস',
    fromStation: 'Chandpur',
    toStation: 'Chittagong',
    departureTime: '05:00',
    arrivalTime: '09:40',
    offDay: 'None',
    fares: { S_CHAIR: 230, SNIGDHA: 440, SHOVON: 190 },
  },
];

// Helper: Convert English Digits to Bengali Digits
const BN_DIGITS: Record<string, string> = {
  '0': '০', '1': '১', '2': '২', '3': '৩', '4': '৪',
  '5': '৫', '6': '৬', '7': '৭', '8': '৮', '9': '৯',
};

export function toBanglaDigits(input: string | number | undefined | null): string {
  if (input === undefined || input === null) return '';
  return String(input).replace(/[0-9]/g, match => BN_DIGITS[match] || match);
}

// Helper: Format DateTime for Bangladesh Railway Ticket
// e.g. "28-09-2026 13:10 (২৮-০৯-২০২৬ ১৩:১০)"
export function formatRailwayDateTime(dateStr: string, timeStr: string): string {
  if (!dateStr) return '';
  const parts = dateStr.split('-');
  const formattedEnDate = parts.length === 3 ? `${parts[2]}-${parts[1]}-${parts[0]}` : dateStr;
  const enFull = `${formattedEnDate} ${timeStr || '00:00'}`;
  const bnFull = toBanglaDigits(enFull);
  return `${enFull} (${bnFull})`;
}

// Helper: Map Station English to Bengali
export function getStationBanglaName(stationName: string): string {
  if (!stationName) return '';
  const match = RAILWAY_STATIONS.find(s => s.name.toLowerCase() === stationName.trim().toLowerCase());
  return match ? match.nameBn : stationName;
}

// Helper: Map Coach English to Bengali
// e.g. THA-92 -> ঠ-৯২, KA-15 -> ক-১৫
const COACH_BN_MAP: Record<string, string> = {
  KA: 'ক', KHA: 'খ', GA: 'গ', GHA: 'ঘ', UMA: 'ঙ',
  CHA: 'চ', CHHA: 'ছ', JA: 'জ', JHA: 'ঝ', IYO: 'ঞ',
  TA: 'ট', THA: 'ঠ', DA: 'ড', DHA: 'ঢ', NA: 'ণ',
  TO: 'ত', THO: 'থ', DO: 'দ', DHO: 'ধ', DNO: 'ন',
  PA: 'প', PHA: 'ফ', FA: 'ফ', BA: 'ব', BHA: 'ভ',
  MA: 'ম', YA: 'য', RA: 'র', LA: 'ল', SHA: 'শ',
  SA: 'স', HA: 'হ',
  // Single letter fallbacks
  T: 'ট', TH: 'ঠ', D: 'ড', DH: 'ঢ', N: 'ণ', P: 'প', PH: 'ফ', F: 'ফ',
  B: 'ব', BH: 'ভ', M: 'ম', Y: 'য', R: 'র', L: 'ল', S: 'শ', H: 'হ', K: 'ক', G: 'গ', J: 'জ',
};

export function formatCoachSeat(coachSeat: string, customBn?: string): string {
  if (!coachSeat) return '';
  if (customBn && customBn.trim()) {
    return `${coachSeat} (${customBn.trim()})`;
  }
  const parts = coachSeat.split('-');
  if (parts.length === 2) {
    const prefix = parts[0].toUpperCase().trim();
    const num = parts[1].trim();
    const bnPrefix = COACH_BN_MAP[prefix] || prefix;
    const bnNum = toBanglaDigits(num);
    return `${coachSeat} (${bnPrefix}-${bnNum})`;
  }
  return `${coachSeat} (${toBanglaDigits(coachSeat)})`;
}
